all:
  vars:
    ip_master: 192.168.1.25
  children:
    master:
      hosts:
        pi6:
          ansible_host: 192.168.1.25
    nodes:
      hosts:
        pi1:
          ansible_host: 192.168.1.20
        pi2:
          ansible_host: 192.168.1.21
        pi3:
          ansible_host: 192.168.1.22
        pi4:
          ansible_host: 192.168.1.23
        pi5:
          ansible_host: 192.168.1.24
